### ISSUE TITLE
Few alignments output

### ISSUE THREAD

**Issue by andrewjmc** [mozack/vdjician#16]
Hello,

I am testing VDJer on a transcriptomic sample. I aligned sequences with STAR (obtaining median read depth of the IGH region of 178, and up to 3000).

I was surprised to only get 52 alignments in the standard SAM file and 120 in sensitive mode.

Is this to be expected given the read coverage? I would be very grateful for your advice and can share further details as required.

Thanks!

**Comment by mozack** [comment]
Hi,  A few factors can impact these results.

In order to assemble a contig in standard mode, we start to see good results at depth 50 - **for a specific clone**.  So, if there are many clones expressed at low levels for example, V'DJer may not identify these.

Also, the read mapping to the assembled contigs requires exact matching.  So, if you are working with error prone reads, you may wind up with a low alignment rate.

**Comment by andrewjmc** [comment]
Thanks!
